---
title: "Day2_pre-analyses_Stroop_2022-01-30"
author: "ML"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(tidyverse) #load dplyr & readr
```

# Pre-analyses data cleaning

## Combining the files
### Day 1

```{r setDF}

d1df_data <- list.files(path = "./Multiplication1",    
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows %>% 
  write_csv("2022-01-30_day1_data-combined.csv")

# no of participants

test<- d1df_data %>% select(participant) %>% unique()
```

### Day 2
```{r df}

d2df_data <- list.files(path = "./Multiplication2",    
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows %>% 
  write_csv("2022-01-30_day2_data-combined.csv")

# no of participants

test<- d2df_data %>% select(participant) %>% unique()
```

## Data Wrangling
### Summary

```{r dataframe1}

# Typing Task

typingdf <- d1df_data %>% 
  select(participant, typedStimulus, typingRT1, typingCorr) %>% 
  filter(typingCorr != "NA") %>% 
  filter(typingCorr == 1) %>% 
  rename(mult_answer = typedStimulus)

# Multiplication fluency task
multiplydf <- d1df_data %>% 
  select(participant, answers, typingRT, multiplyCorr) %>% 
  filter(multiplyCorr != "NA")

```

```{r dataframe}

keyProcessingdf <- d2df_data %>% 
  select(participant, positionLayout, rt_resp_4.corr, rt_resp_4.rt) %>% 
  filter(positionLayout !="NA") %>% 
  filter(rt_resp_4.corr ==1) %>% 
  filter(participant != "749") #underperformed participant

sizeCongruitydf <- d2df_data %>% 
  select(participant, displayProblem, numDistance, 
         leftNo_size, rightNo_size, Dims, 
         ct_keyResp.corr, ct_keyResp.rt) %>% 
  filter(Dims != "NA") %>% 
  filter(participant != "749") #underperformed participant

stroopMultiplydf <- d2df_data %>% 
  select(participant, multliplyProblem, mult_answer, 
         physicalSize, orderOperand, 
         multi_RT, multiplyCorr) %>% 
  filter(multliplyProblem != "NA") %>% 
  filter(multiplyCorr == 1)
```

### Summary

```{r dfsummary1}

# Summary of average typing speed
avgTyping <- typingdf %>% 
  filter(typingCorr == 1) %>% 
  group_by(participant) %>% 
  summarise(avgTypingRT = mean(typingRT1))

# Summary of multiplication fluency
multiplyFluency <- multiplydf %>% 
  filter(multiplyCorr == 1) %>% 
  group_by(participant) %>% 
  summarise(totalCorr = sum(multiplyCorr))

# Combined data
comb_typingFluency <- typingdf %>% 
  inner_join(stroopMultiplydf, c ("participant", "mult_answer")) %>% 
  inner_join(multiplyFluency, by = c("participant"))
```


## Summary data
### Processing speed, numerical comparison, numerical stroop

```{r dfsummary2}

keyPressAvgSpeed <- keyProcessingdf %>% 
  group_by(participant) %>% 
  summarise(keyPressRT = mean(rt_resp_4.rt)) %>% 
  ungroup()

sizeCongruityRT <- sizeCongruitydf %>% 
  filter(ct_keyResp.corr == 1) %>% 
  group_by(participant, Dims) %>% 
  summarise(congruityRT = mean(ct_keyResp.rt))

stroopMultiplyRT <- stroopMultiplydf %>% 
  filter(multiplyCorr == 1) %>% 
  group_by(participant, physicalSize) %>% 
  summarise(stroopRT = mean(multi_RT))

comb_ps_sc_stroop <- keyPressAvgSpeed %>% 
  inner_join(sizeCongruityRT, c("participant")) %>% 
  inner_join(stroopMultiplyRT, c("participant")) %>% 
  inner_join(comb_typingFluency, c("participant"))
  

```

## Combined files

```{r}



```



## Regression

```{r regress}

library(performance)
library(lme4)
library(lmerTest)

## Model 1: predict the stroop RT from typing speed and fluency

model1 <- lmer(multi_RT ~ typingRT1 + physicalSize + (1|participant) + (1| mult_answer), data = comb_typingFluency)
summary(model1)
# No order effect for operand
### Calculating t-value and p-value
tvals_model1 <- fixef(model1)/sqrt(diag(vcov(model1)))
tvals_model1

### Getting p-values
2*(1-pnorm(abs(tvals_model1)))
### Getting confidence interval
confint(model1)
model_performance(model1)
```


```{r}

# Model 2: Fluency on size congruity task performance

comb_sizeCongruity <- sizeCongruitydf %>% 
  inner_join(multiplyFluency, c("participant")) %>% 
  filter(ct_keyResp.corr == 1)

model2 <- lmer(ct_keyResp.rt ~ totalCorr + Dims + (1|participant) + (1|displayProblem), 
               data = comb_sizeCongruity)

summary(model2)
```

